AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  TODO

Globals:
  Function:
    Timeout: 20

Resources:
  GithubBioStatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: GithubBioStatsFunction
      Handler: githubbiostats.App::handleEvent
      Runtime: java11
      MemorySize: 512
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Name: github-bio-stats-schedule
            Description: TODO
            Enabled: True

Outputs:
  GithubBioStatsFunction:
    Description: "TODO"
    Value: !GetAtt GithubBioStatsFunction.Arn
  GithubBioStatsFunctionIamRole:
    Description: "Implicit IAM Role created for GithubBioStatsFunction"
    Value: !GetAtt GithubBioStatsFunctionRole.Arn